# Site settings
title: Nicole & Jöran
email: joeran.riess@googlemail.com
url: https://joeni-heiraten.de
description: "Wir heiraten!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: 

# Build settings
markdown: kramdown
permalink: pretty
